### PR TITLE
Design a new logo and add it to our pages

### PR DESCRIPTION
**Pull request by smddzcy**
## About

* **Related Issues:** https://github.com/bounswe/bounswe2017group5/issues/89

As discussed in the issue above, I designed a logo and put it on all our pages - including a big one on the homepage.

### Changes

- Design a new logo and add 2 versions of it to our assets: orange (`logo.png`) and white (`logo-white.png`). They both have transparent backgrounds.
- Add our logo to the navbar and homepage.

## Visuals
**Note:** There's been a minor change on these visuals: Our logo color is now `#FF9500`, which is our primary color. It is same as what you see on navbar and button backgrounds.

### Desktop
screencapture-file-users-smddzcy-bounswe2017group5-fe-index-html-1508965743144

### Mobile (iPhone 6 screen size)
screencapture-file-users-smddzcy-bounswe2017group5-fe-index-html-1508966104242

## Testing

- Open homepage in different browsers that we support (last 2 versions of Chrome and Firefox, IE 11, Safari etc.)
- Check whether logos look properly in different screen sizes on all those browsers.

### CODE REVIEW

**Review by karacasoft — CHANGES_REQUESTED** [review]
The logo looks faded out. Could you give it the original interestr color? The one you used on the top bar?

**Comment by smddzcy** [comment]
@triforce930 Seems legit.. I'll fix this one and start on my other tasks (presentation etc.) on Sunday. I don't have much (actually any) time until then.

**Comment by karacasoft** [comment]
It's all right. Fix this one and you're free. :V

**Comment by smddzcy** [comment]
@triforce930 With these last commits, I shall claim my freedom. Review please.

**Review by karacasoft — APPROVED** [review]
You'll never be truly free, unless you leave proprietary software... :V https://xkcd.com/225/

Approved :+1:

**Pull request merged**
