### PR TITLE
add Login and Register pages

### PR DESCRIPTION
**Pull request by yfenes**
## About

Login and Register pages are added.

Redirects are not set for now.
There can be 2 users with same email, we have to fix that later.

Please review.

### CODE REVIEW

**Comment by karacasoft** [comment]
#100

**Comment by smddzcy** [comment]
Can you please remove all `.DS_Store` files and add `.DS_Store` to `.gitignore`?

**Comment by karacasoft** [comment]
@smddzcy .DS_Store files will be removed with this https://github.com/bounswe/bounswe2017group5/commit/29e6845998b3e2b254ea1b812169c9700be6a3d4 don't know if they appear again with the merge commit, but we can just remove them again, it's fine.

**Review by karacasoft — APPROVED** [review]
We only wanted the backend to work, and, it works fine. So, I'm merging this.

**Pull request merged**
