### PR TITLE
Fix "Improvement/api reduce data"

### PR DESCRIPTION
**Pull request by Morgazipa**
##  About ##
- related pull requests: #171 

In the pull request referenced above, the data template serializer is changed to include basic user and group info. However, since the same endpoint was used for template creation using only id's of group and user, the template creation was broken. This PR is meant to fix this issue.

## Changes ##
- Add another serializer that uses only id's in relations to other objects
- Change the serializer class used depending on the method of the request, i.e.  include user info with GET requests

### CODE REVIEW

**Comment by smddzcy** [comment]
I'll let @triforce930 review this one since he's the owner of the fixed PR 👌

**Comment by karacasoft** [comment]
At some parts, the changes I want were reverted. I won't accept this but will fix the error by myself since it's my mistake at the first place. The live version will be bugged for now. We can revert master to its previous version if it's urgently required by any of the team members.

**Comment by karacasoft** [comment]
I'll suggest leaving this around though, if I change my mind and want to revert back my changes anyway

**Comment by karacasoft** [comment]
I think I'll accept these changes and create a new module for serializers I want

**Review by karacasoft — DISMISSED** [review]

**Comment by Morgazipa** [comment]
Oops. I seem to have reverted unknowingly some other changes while playing with Git. I did reset that commit and hope everything works fine know.

**Review by karacasoft — APPROVED** [review]
Very nice. This fixes the problem. And keeps my changes. Perfect.

**Pull request merged**
