### PR TITLE
Basic search for groups, users and bug fix with the unique email

### PR DESCRIPTION
**Pull request by murat0431**
I added basic search for our api. It filters group and user results. Groups are filtered according to the name field. Users are filtered according to username field. For now please take a look at my changes. If there is a problem with my logic let me know :)

Edit: I also added two functions to forms.py to solve the problem with the unique email (Related issue #150 )

### CODE REVIEW

**Review by smddzcy — CHANGES_REQUESTED** [review]
Looks great. I'll approve after you add some tests 👍

**Comment by murat0431** [comment]
👍

**Comment by murat0431** [comment]
I added some tests for the search. Please review

**Comment by murat0431** [comment]
2. milestone is tomorrow so if someone review this PR as soon as possible, that would be great :)

**Review by smddzcy — APPROVED** [review]

**Pull request merged**
