### PR TITLE
[WIP] Frontend for annotations with a Firefox add-on

### PR DESCRIPTION
**Pull request by ThoAppelsin**
## About

* **Related Issues:** #182 and #181 
* **Related Pull Requests:** #204 

This pull request aims to bring annotations to our application with a plugin for Firefox 57.

It is almost complete. Demonstrably complete, in fact. I hope to add a couple of more before we merge it with the master. If you wish, however, you can just do it __after adding the address of our website to `allowedHosts` array within `sidebar/panel.js`__.

Also, please make sure that everything will also work on the server on remote. Check the addresses, etc. Check them on the back-end, too, please.

Features to come (may not be there before the demo):
- [x] ID's on post containers for more specific CSS selectors.
- [ ] Disabling of sidebar with the press on the "Dismiss" button.
- [ ] Keeping sidebar disabled until the connection is established between content script and the sidebar. This will also make the sidebar truly disabled when the user is on an unsupported website.
- [ ] Keeping the annotations of the users in-memory, allowing them to change their selections without having to worry about losing them. They do lose them now.

### Changes

- Slight changes on the back-end for annotations.
- Addition of the plugin located at the `firefoxaddon` directory.

## Visuals

screen shot 2017-12-28 at 14 28 49

## Usage

- Navigate to `about:debugging` on your browser
- Load the `firefoxaddon/manifest.json` as a temporary add-on from that window
- Switch to the Interestr website

### CODE REVIEW

**Comment by smddzcy** [comment]
It looks cool, can we merge?

**Review by smddzcy — DISMISSED** [review]

**Comment by smddzcy** [comment]
Tests are failing though, please run `python manage.py makemigrations --merge`  and commit the new merge migration.

**Comment by ThoAppelsin** [comment]
I pulled the master, should be OK now. I was working on the disabling features, however. Will you merge without them?

It is actually fine to do so. It would be great if we had some annotations on our website instead of the lousy disabling. We can hotfix disabling into the system anyway. Disabling of the add-on, does not even require an update on the server, anyway.

**Comment by ThoAppelsin** [comment]
But __please__ do check the back-end to see if there is anything specific about 127.0.0.1 or interestr.com, that may cause problems when pushed onto the server where the ip address is 35, something.

**Review by smddzcy — APPROVED** [review]

**Pull request merged**
