### PR TITLE
Template Based Search (Backend)

### PR DESCRIPTION
**Pull request by Morgazipa**
## About

* **Related Issues:** #180 

To initiate the effort, I implemented a backend view for template based search. It accepts template id and a list of constraints, and returns a list of posts which satisfy each constraint simultaneously. At the moment, no validation of any sort is done.  Supported filtering query types are "greater than", "less than", "equals" and "contains".  A simple test is given for the purpose of illustration. The search makes use of JSON query capabilities of PostgreSQL. Also, "OR" combinations of queries are not possible.

Any feedback/change request is welcome.

### Changes

- Created a view  for template based search
- Add an endpoint 
- Add a very simple test for it

### CODE REVIEW

**Comment by smddzcy** [comment]
Looks cool. I'll test it and implement its frontend if it works 👌

**Review by smddzcy — APPROVED** [review]
I've tested it on my local, it seems to be working very well. Thanks 👌 I just added one commit to handle the edge cases, please take a look at it if you want.

It's a good starting point, but it's definitely not complete. I think we should merge it as it is and improve it after the other tasks. 

p.s. See my comment below for 2 tests - search with default and some other template.

**Comment by smddzcy** [comment]
# Default Template Search (no `template_id`)
screen shot 2017-12-25 at 23 57 36
screen shot 2017-12-25 at 23 57 16

# Some Other Template Search
screen shot 2017-12-25 at 23 58 30
screen shot 2017-12-25 at 23 58 48

(`results` array is a little big, so only the `data` part is shown here which is enough I guess)

**Comment by Morgazipa** [comment]
Thanks for both review and edge case handling. If it is okay for frontend team, it is also okay for me :D

**Comment by smddzcy** [comment]
_Frontend team_, sure... 😴

**Pull request merged**
