### PR TITLE
Fixed #98 - failing post tests

### LINKED ISSUE #98: One of the tests written for Posts fails for no reason
## About

* **Related Issues:** #91 

When I run the tests the test named `test_existing_post` fails. But I can see that posts return fine when I run the API itself.

### PR DESCRIPTION
**Pull request by iremUlutas**
Update data_template in order to have a default JSONField, fields.

## About

* **Related Issues:** 98

Bug Fix with Failing Post Tests.

### Changes
Update data_template model to have a default value.

### CODE REVIEW

**Comment by iremUlutas** [comment]
@triforce930 please ignore this for the reviewers were not set properly.

**Comment by karacasoft** [comment]
You may close this if you don't want this to merge anymore

**Comment by karacasoft** [comment]
... you also should be able to change the reviewers, too. I'll be looking at the #122 though, since you have already opened it anyways

**Comment by iremUlutas** [comment]
Nope, this shouldn't be merged anymore. Closing.

**Pull request closed without merging**
