### PR TITLE
Data templates CRUD UI

### LINKED ISSUE #127: Prepare web-frontend elements for template creation, viewing, usage and posting
## About

As per [19th meeting notes](../wiki/Meeting-19--14.11.2017), we have to integrate the template functionalities from backend to the web-frontend.

We have agreed to give ourselves one week to implement it. However, it would be really good if we were to do it until 13:00 this Thursday (16 November), as promised to our customer. It isn't likely to happen, since we have only ~38 hours left, and two nights to sleep.

## To-do

- [x] Template creation view.
- [x] Listing of templates per group.
- [x] Template selection and activation.
- [x] Template posting.

### PR DESCRIPTION
**Pull request by ThoAppelsin**
## About

* **Related Issues:** #127

We ought to implement the UI for preparation, creation and usage of the data templates. The preparation and creation parts are coarsely done, i.e. looks bad but functionally OK. As for the usage, the user can see the available templates, switch to them, however may not share a post with them.

### Changes

All the changes are on the group details page.

- A modal pops up for template creation.
- One of the three fields can be added to the template: Checkbox, Multiple Selection, and Text Area.
- Labels and legends can be edited through clicking, finalized through clicking away or hitting enter.
- "Create!" button submits the template creation form, into the database.

- Dropdown is now only for selecting the active template, creation is a separate button.
- Dropdown now properly displays the templates of the group.
- Two more buttons are for editing and extending the currently selected template, but not yet functional.

- Sharing posts through templates is not yet available.

## Visuals

See the below comment from @smddzcy.

## Testing

How can this contribution be tested? Use the following structure:

- Assuming your database already has a user and at least one group.
- Click the "Create Template" button.
- Prepare a template through the "+" button and editing labels as described above.
- Submit the template.

- Check back the template on the group details page.
- Check if the template is available on the group details page of another group.

- And more...

---

Closes #127

### CODE REVIEW

**Comment by smddzcy** [comment]
I just made some contributions to this PR:

- Implemented missing template field types (basically all the input types like text, number and so on)
- Implemented edit template functionality
- Implemented remove template functionality
- Implemented add option functionality for multiple select template field type
- Improved the styling of everything
- Added an open-source library for good looking alerts and prompts (see the examples below)

Be aware that **we still can't share a post with a template**, because it's just the UI part. Posting is connected to the backend yet 😄 

# Visuals

## Template Create/Edit/Remove
template-stuff

## Default Template Edit/Remove
template-default

## Multiselect Field Adding Options 
template-mult-opt

---

All features are tested on **Chrome 62**, **macOS 10.13.1**.

**Comment by smddzcy** [comment]
@triforce930 Review, please 👓

**Comment by karacasoft** [comment]
Wow, this looks amazing. Accepted :+1:, I guess...

**Review by karacasoft — DISMISSED** [review]

**Review by karacasoft — DISMISSED** [review]

**Review by Morgazipa — COMMENTED** [review]
I tried to reproduce these fantastic results in 56.0.2. Apparently, "href=#" statements cause an issue in Firefox as I get lots of "Empty string passed to getElementById()." . Also js file for sweetalert dependency seems to be misssing if I am not mistaken.

**Comment by smddzcy** [comment]
@Morgazipa Thanks for checking, you're right, it wasn't working in Firefox. I made some fixes, now it works 👍 Tested in **Firefox 57 (Quantum)**.

**Comment by smddzcy** [comment]
@triforce930 Review, please 👓

**Comment by Morgazipa** [comment]
I can confirm that all these now work very smoothly on my browser too 👍

**Pull request merged**
